export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const FETCH_POPULAR_SERIES = 'FETCH_POPULAR_SERIES';
export const FETCH_POPULAR_SERIAL = 'FETCH_POPULAR_SERIAL';